//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibrosRevistas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autores> autores { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<estudiantes_revistas_libros> estudiantes_revistas_libros { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<revistas> revistas { get; set; }
        public virtual DbSet<revistas_libros> revistas_libros { get; set; }
        public virtual DbSet<tipo_revistas> tipo_revistas { get; set; }
    }
}
