//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLibrosRevistas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revistas_libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public revistas_libros()
        {
            this.estudiantes_revistas_libros = new HashSet<estudiantes_revistas_libros>();
            this.libros = new HashSet<libros>();
            this.revistas = new HashSet<revistas>();
        }
    
        public int id_Informacion { get; set; }
        public Nullable<int> numero_paginas { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string descripcion_general { get; set; }
        public string editorial { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudiantes_revistas_libros> estudiantes_revistas_libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libros> libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<revistas> revistas { get; set; }
    }
}
